### PR TITLE
[PR] Creating `nextra` with auth

### PR DESCRIPTION
**Pull request by LuchoTurtle**
addresses #1 

This PR adds a new `Nextra` project that has been modified to accommodate the requirements of #1 . 

Authentication has been added successfully, and routes have been protected.

Going to check the `Search` requirement, although I feel like this will entail using a `custom-theme`, which is a heavy workload. Will look into it 🔎

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
Meanwhile, I was trying to get `i18n` to work for future requirements (Arabic support) and ran into the same issue as https://github.com/shuding/nextra/issues/2962. I've commented to provide my insights.

**Comment by nelsonic** [comment]
Cool. 👌 
I feel like there’s already enough in this PR to showcase. 
So assign when you feel it’s reviewable/mergable. 👌

**Comment by nelsonic** [comment]
On this branch, ran:
```sh
pnpm i 
pnpm run dev
```

Get: 

image

So filling in the gaps for running the finished version of the project. 🧑‍💻

**Comment by LuchoTurtle** [comment]
That's weird. I've deleted both `.next` and `node_modules` on both the root and inside `theme` directory and ran `pnpm i` and `pnpm run dev` and it works on my end.

Besides that, you're going to need to complete `.env.local-example` (and rename it to `.env.local`, as per the docs). You ought to follow the docs to create a Github App and secret to use in the `.env` file.

**Comment by nelsonic** [comment]
image

image

_Really_ don't like how `nextra` prefixes all `Tailwind` classes with `nx-` 
image
totally pointless extra typing 🤦‍♂️ 

Given the choice, I _definitely_ wouldn't use `Nextra` for a docs project there are _so many_ steps, config files and unnecessary complexity for a suboptimal result. The `theme/src/components/flexsearch.tsx` is `~300loc` of undocumented code which in turn invokes `theme/src/components/search.tsx` `~300loc` of undocumented code. 🤦‍♂️ 

It's clear that this is meant to be run "as is" and not customised very much. 

Constantly seeing the **Error** that it cannot validate the `_meta.json` is infuriating:
```sh
[nextra-theme-docs] Error validating _meta.json file for "reference_api" property.

Unrecognized key(s) in object: 'private'
[nextra-theme-docs] Error validating _meta.json file for "mega_private" property.

Unrecognized key(s) in object: 'private'
 GET /_next/data/development/reference_api/person.json 200 in 814ms
```
And taking `814ms` to render a page that hasn't changed. 🐌 🤷‍♂️ 

I clearly need to get better at giving precise requirements. 💭  
this is why we end up with so many micro-managers. .. 😢 

All we wanted was a way to _streamline_ the process of writing docs from `docusaurus` ...
Instead we get 30kloc of PR that very few people will be able to _understand_ much less _maintain_
and _more_ complexity for writing docs. 
No wonder everyone is using [`notion`](https://github.com/dwyl/product-ux-research/issues/5#issuecomment-647495254) ... why would anyone waste their time on something _even_ more complex?! 🤷‍♂️ 

I'm definitely not "happy" with this. 
If I could use one emoji to describe how I feel it's:

# 😿 

@LuchoTurtle I think given the circumstances and _incomplete_ instructions you've done a _good_ job. 

The `tutorial.md` (split out of `README.md`) is **`42 pages`**: 
nextra-demo-doc-42-pages

How many people do you think will read/follow it? 💭 

I'm frustrated at the complexity of `Nextra` ... as I'm sure you must have been for the past few weeks. ⏳ 
Definitely not a reflection on _you_; you didn't _choose_ this tech/tool you just rolled with it! 👌 

Anyway, merging. :shipit:

**Review by nelsonic — APPROVED** [review]
Thanks @LuchoTurtle 👌

**Comment by LuchoTurtle** [comment]
Just adding a few comments:
- I fully agree that `Nextra` is meant to be used as-is, given the limited customization options. The work done in this PR was meant to allow the person to have easy control of private routes dynamically by embedding this functionality within the `_meta.json` (hence why you get the warnings from `Nextra` saying they don't recognize my added `private` property - it is foreign to it).
- taking `814ms` to render a page that hasn't changed is fair when running in development mode. If the site is `built` and then `npm start` using the built site in production mode, it is much faster. Though, I agree that having these compile times in the development cycle can be cumbersome.
- `"I clearly need to get better at giving precise requirements. 💭 this is why we end up with so many micro-managers. .. 😢"` can't help but think this a politically correct way of you saying I misinterpreted the requirements. This can be a fair assertion, since I can understand your frustration on dealing with a `30k`-line PR like this where you wanted to `KISS`. Though I may be wrong! :p 
- the code we will be using in `/docs` for `A` will be much more pleasant to work with. I learnt a lot with `Nextra` and its nuances in this PR, so I'm positive the monorepo approach we're having at A's `/docs` will be much more manageable (even if it's not _optimal_ having 3 projects running as a standalone unit, I agree with you on that). 

Thanks for taking the time to review this, it's mighty appreciated! 🙏

**Comment by nelsonic** [comment]
The `recipient` of the message should _never_ be responsible for interpreting the message.
That's how we end up with legal "interpretations" and "grey areas" which [waste time](https://github.com/dwyl/start-here/blob/main/manifesto.md#your-time-should-never-be-wasted).
The onus is _always_ on the person transmitting the message - this case me - to ensure the message is as clear as possible. I will be better. 🔰 👌

**Pull request merged**
